### PR TITLE
Fix renderflex bug

### LINKED ISSUE #100: Renderflex overflow
On the Signup page and the first page there is a Renderflex overflow error

### PR DESCRIPTION
**Pull request by AstridBer**
This commit fixes the renderflex overflow error on the first page and the sign up page. It also fixes some inconsistencies in the text 
fixes #100

### CODE REVIEW

**Review by InaJ123 — APPROVED** [review]

File: smart_pet_buddy/lib/main.dart [hunk 1]
```diff
@@ -66,77 +65,79 @@ class SmartPetBuddy extends StatelessWidget {
...
-                        side: BorderSide(color: textColor),
-                        borderRadius: BorderRadius.circular(50)),
-                    child: Text(
-                      "Login",
-                      style: TextStyle(
-                          color: textColor,
-                          fontWeight: FontWeight.w800,
-                          fontSize: 25,
-                          fontFamily: 'Nexa Rust'),
+          child: SingleChildScrollView(
```
Comment (InaJ123) [inline smart_pet_buddy/lib/main.dart:68]: Nice!
